import { Navigation } from "../components/Navigation"
import '../styles/globals.css'

export const metadata = {
  title: 'Probando Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <Navigation></Navigation>
        {children}
      </body>
    </html>
  )
}
